# Generated by Django 4.2.1 on 2023-06-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeviocApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=None, upload_to='service/'),
            preserve_default=False,
        ),
    ]
