# Generated by Django 4.2.1 on 2023-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeviocApp', '0002_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='pokeviocApp/static/media/service/'),
        ),
    ]
